### ISSUE TITLE
Feature: ComfyUI model directory support

### ISSUE THREAD

**Issue by aarongerber** [lllyasviel/stable-diffusion-webui-forge#934]
There isn’t a simple way to point to a folder that has comfy model structure and have the software live in that directory. Would be great if that was possible. Sometimes Comfy is where it is at for a convoluted solution, and other times I wish I had the simplicity of Forge.

**Comment by zefie** [comment]
You can reverse it and have comfy use the WebUI structre by providing `extra_model_paths.yaml` to ComfyUI:

```yaml
#config for a1111 ui
# change base_path to match the root of your A1111/Forge WebUI models folder
# change configs to your ComfyUI config folder (or comment it out to use the default)

   a1111:
    base_path: /models
    configs: /home/runner

    checkpoints: Stable-diffusion
    vae: VAE
    loras: |
         Lora
         LyCORIS
    upscale_models: |
                  ESRGAN
                  RealESRGAN
                  SwinIR
                  upscale_models
    embeddings: embeddings
    hypernetworks: hypernetworks
    controlnet: ControlNet
    clip_vision: clip_vision
```

Note that for WebUI to share embeddings with Comfy, I moved the embeddings folder into the models, and replaced the old path with a symlink.
